### ISSUE TITLE
Issue-Add files via upload

### ISSUE THREAD

**Issue by Epic-SX** [JamesRyo/test123#22]
Automated Review Comments
Issues in OpenCVAnim.py:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
Issues in OpenCVAnimOperator.py:
  - (33, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (67, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')
  - (83, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')
  - (93, 'Hardcoded string found')
  - (98, 'Line exceeds 80 characters')
  - (105, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (138, 'Line exceeds 80 characters')
  - (141, 'Line exceeds 80 characters')
  - (142, 'Line exceeds 80 characters')
  - (143, 'Line exceeds 80 characters')
  - (144, 'Line exceeds 80 characters')
  - (147, 'Line exceeds 80 characters')
  - (151, 'Line exceeds 80 characters')
  - (152, 'Line exceeds 80 characters')
  - (153, 'Line exceeds 80 characters')
  - (156, 'Line exceeds 80 characters')
  - (157, 'Line exceeds 80 characters')
  - (167, 'Line exceeds 80 characters')
  - (168, 'Line exceeds 80 characters')
  - (169, 'Line exceeds 80 characters')
  - (171, 'Line exceeds 80 characters')
  - (174, 'Line exceeds 80 characters')
  - (175, 'Line exceeds 80 characters')
  - (177, 'Line exceeds 80 characters')
  - (177, 'Hardcoded string found')
  - (180, 'Line exceeds 80 characters')
  - (181, 'Line exceeds 80 characters')
  - (183, 'Line exceeds 80 characters')
  - (183, 'Hardcoded string found')
  - (184, 'Line exceeds 80 characters')
  - (184, 'Hardcoded string found')
  - (187, 'Line exceeds 80 characters')
  - (188, 'Line exceeds 80 characters')
  - (189, 'Line exceeds 80 characters')
  - (190, 'Line exceeds 80 characters')
  - (191, 'Line exceeds 80 characters')
  - (192, 'Line exceeds 80 characters')
  - (193, 'Line exceeds 80 characters')
  - (195, 'Line exceeds 80 characters')
  - (195, 'Hardcoded string found')
  - (196, 'Line exceeds 80 characters')
  - (196, 'Hardcoded string found')
  - (197, 'Line exceeds 80 characters')
  - (197, 'Hardcoded string found')
  - (198, 'Line exceeds 80 characters')
  - (198, 'Hardcoded string found')
  - (209, 'Hardcoded string found')

**Comment by horizonreach** [comment]
I got it.
